variables:
  DOCKER_IMAGE: registry.taphoaictu.id.vn:4443/user_pg/${CI_PROJECT_NAME}:${CI_COMMIT_TAG}_${CI_COMMIT_SHORT_SHA}
  DOCKER_CONTAINER: user_pg
  BASE_DIRECTORY: /home/QLNH/user_pg

stages:
  - clone
  - buildandpush
  - deploy
  - showlog

clone:
  stage: clone
  variables:
    GIT_STRATEGY: none
  script:
    - |
      if [ ! -d "$BASE_DIRECTORY/.git" ]; then
        git clone https://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@github.com/ducvubo/user-pg $BASE_DIRECTORY
      else
        cd $BASE_DIRECTORY
        git reset --hard
        git checkout main
        git pull origin main
      fi
  tags:
    - vuducb
  only:
    - tags


buildandpush:
  stage: buildandpush
  variables:
    GIT_STRATEGY: clone
  before_script:
    - docker login registry.taphoaictu.id.vn:4443 -u vuducbo -p Duc17052003*
  script:
    - cd $BASE_DIRECTORY
    - docker build -t $DOCKER_IMAGE .
    - docker push $DOCKER_IMAGE
  tags:
    - vuducb
  only:
    - tags

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  before_script:
    - docker login registry.taphoaictu.id.vn:4443 -u vuducbo -p Duc17052003*
  script:
    - cd $BASE_DIRECTORY
    - docker network inspect backend_qlnh_network || docker network create backend_qlnh_network
    - docker pull $DOCKER_IMAGE
    - docker rm -f $DOCKER_CONTAINER
    - docker run -d --name $DOCKER_CONTAINER -p 3001:3001 --network backend_qlnh_network $DOCKER_IMAGE
  tags:
    - vuducb
  only:
    - tags

showlog:
  stage: showlog
  variables:
    GIT_STRATEGY: clone
  script:
    - sleep 20
    - docker logs $DOCKER_CONTAINER
  tags:
    - vuducb
  only:
    - tags