import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { Toaster } from '@/components/ui/toaster'
import { cookies } from 'next/headers'
import { v4 as uuidv4 } from 'uuid'
const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'USER_PG',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  // const cookie = await cookies()
  // const id_user_guest = cookie.get('id_user_guest')?.value
  // if (!id_user_guest) {
  //   cookie.set({
  //     name: 'id_user_guest',
  //     value: 'guest-id-' + uuidv4(),
  //     maxAge: 60 * 60 * 24 * 365 * 10
  //   })
  // }
  return (
    <html lang='en'>
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Toaster />
        {children}
      </body>
    </html>
  )
}
